import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "en" | "am";
const messages: Record<Language, Record<string, string>> = {
  en: {
    "common.back": "Back to marketplace", "common.signOut": "Sign out", "common.loading": "Loading…", "common.save": "Save", "common.cancel": "Cancel", "common.refresh": "Refresh", "common.open": "Open", "common.submit": "Submit", "common.status": "Status",
    "nav.owner": "Owner portal", "nav.admin": "Admin portal", "nav.account": "My account", "nav.winners": "Winner gallery", "nav.auctions": "Auctions",
    "owner.title": "Owner portal", "owner.subtitle": "Manage your product listings and auction submissions.", "owner.applyTitle": "Apply for a seller portal", "owner.applyBody": "Tell the Cherta team about your seller business. Approved owners can submit product auctions for review.", "owner.business": "Business / seller name", "owner.city": "City", "owner.phone": "Contact phone", "owner.description": "About your products", "owner.apply": "Send owner application", "owner.pending": "Your owner application is being reviewed.", "owner.rejected": "Your previous application was not approved. You may submit an updated application.", "owner.approved": "Verified seller access", "owner.newAuction": "Create product auction", "owner.myListings": "My listings", "owner.reviewHint": "New owner listings go to the administrator for approval before appearing in the public marketplace.", "owner.submitReview": "Submit for review", "owner.empty": "No listings yet. Create your first product auction.", "owner.applied": "Application submitted.", "owner.created": "Listing saved and submitted for review.",
    "auction.title": "Auction details", "auction.description": "Product details", "auction.seller": "Seller", "auction.fee": "Participation fee", "auction.range": "Allowed bid range", "auction.maxBids": "Maximum bids per account", "auction.start": "Opens", "auction.end": "Closes", "auction.currentCount": "Recorded bids", "auction.placeBid": "Place a bid", "auction.amount": "Your bid (ETB)", "auction.paymentRequired": "Submit a transaction number or receipt screenshot for administrator review. Bid only after verification.", "auction.paymentReady": "Verified payment available", "auction.submitBid": "Submit bid", "auction.signInBid": "Sign in to bid", "auction.report": "Report listing", "auction.reportTitle": "Report this listing", "auction.reportSubject": "Subject", "auction.reportDetails": "Details", "auction.sendReport": "Send report", "auction.timeClosed": "This auction is not accepting bids.", "auction.bidSuccess": "Your bid was accepted by the server.",
    "winners.title": "Winner gallery", "winners.subtitle": "Published results with references you can verify.", "winners.search": "Search products, winner, or reference…", "winners.all": "All results", "winners.winner": "Winner", "winners.none": "No unique bid", "winners.empty": "No published results yet.", "winners.reference": "Reference", "winners.integrity": "Integrity hash", "winners.bids": "valid bids", "winners.phone": "Masked phone",
    "account.notifications": "Notifications", "account.devices": "Signed-in devices", "account.ownerAccess": "Apply for seller access", "account.openOwner": "Open owner portal", "account.markRead": "Mark read", "account.currentDevice": "This device", "account.reply": "Administrator response", "account.noNotifications": "You are all caught up.", "account.deviceBody": "This browser is recorded for account security. Sign out on devices you do not recognize.",
    "admin.ownerApplications": "Owner applications", "admin.listingReview": "Listing review", "admin.ownerApprove": "Approve owner", "admin.ownerReject": "Reject application", "admin.approveListing": "Approve and publish", "admin.rejectListing": "Reject listing", "admin.reply": "Response to bidder", "admin.privateNote": "Private admin note", "admin.saveReview": "Save response", "admin.ownerPending": "Waiting for review", "admin.noApplications": "No owner applications are pending.", "admin.noListings": "No listings are waiting for review.",
    "form.title": "Product title", "form.category": "Category", "form.description": "Product description", "form.seller": "Seller display name", "form.image": "Product image", "form.imageHint": "JPEG, PNG or WebP; compressed and stored in Firestore under 300 KB", "form.fee": "Bid fee (ETB)", "form.minimum": "Minimum bid (ETB)", "form.maximum": "Maximum bid (ETB)", "form.limit": "Max bids per user", "form.opens": "Opens", "form.closes": "Closes", "form.createDraft": "Save draft", "form.uploading": "Preparing image for Firestore…", "form.saving": "Saving…", "form.imageRequired": "Choose a product image first.",
    "notice.bidAccepted.title": "Bid received", "notice.bidAccepted.body": "Your bid of {amount} ETB for {title} was recorded.", "notice.auctionResult.title": "Auction result published", "notice.auctionResult.body": "The result for {title} is now available.", "notice.reportUpdate.title": "Support report updated", "notice.reportUpdate.body": "Your report “{subject}” is now {status}.", "notice.ownerApproved.title": "Owner access approved", "notice.ownerApproved.body": "Your seller portal access is active. You can now create listings.", "notice.ownerRejected.title": "Owner application update", "notice.ownerRejected.body": "Your owner application was not approved. Check your account for an administrator note.", "notice.auctionApproved.title": "Listing approved", "notice.auctionApproved.body": "Your listing {title} is approved and published.", "notice.auctionRejected.title": "Listing needs changes", "notice.auctionRejected.body": "Your listing {title} was returned for review. {note}", "notice.paymentApproved.title": "Payment verified", "notice.paymentApproved.body": "Your payment for {auction} was verified. You can now place a bid.", "notice.paymentRejected.title": "Payment proof not approved", "notice.paymentRejected.body": "Your payment proof for {auction} was not approved. Contact support if you need help. {note}", "notice.default.title": "Cherta update", "notice.default.body": "There is a new update in your account."
  },
  am: {
    "common.back": "ወደ ገበያው ተመለስ", "common.signOut": "ውጣ", "common.loading": "በመጫን ላይ…", "common.save": "አስቀምጥ", "common.cancel": "ሰርዝ", "common.refresh": "አድስ", "common.open": "ክፈት", "common.submit": "ላክ", "common.status": "ሁኔታ",
    "nav.owner": "የሻጭ ፖርታል", "nav.admin": "የአስተዳዳሪ ፖርታል", "nav.account": "መለያዬ", "nav.winners": "የአሸናፊዎች ጋለሪ", "nav.auctions": "ጨረታዎች",
    "owner.title": "የሻጭ ፖርታል", "owner.subtitle": "የምርት ዝርዝሮችዎንና የጨረታ ጥያቄዎችዎን ያስተዳድሩ።", "owner.applyTitle": "የሻጭ ፖርታል ለማግኘት ያመልክቱ", "owner.applyBody": "ስለ ሻጭ ንግድዎ ለ Cherta ቡድን ይንገሩ። የተፈቀዱ ሻጮች ምርቶችን ለጨረታ ግምገማ ያቀርባሉ።", "owner.business": "የንግድ/ሻጭ ስም", "owner.city": "ከተማ", "owner.phone": "ስልክ", "owner.description": "ስለ ምርቶችዎ", "owner.apply": "የሻጭ ማመልከቻ ላክ", "owner.pending": "የሻጭ ማመልከቻዎ እየተገመገመ ነው።", "owner.rejected": "የቀድሞ ማመልከቻዎ አልተፈቀደም። የተሻሻለ ማመልከቻ ማቅረብ ይችላሉ።", "owner.approved": "የተረጋገጠ ሻጭ መዳረሻ", "owner.newAuction": "የምርት ጨረታ ፍጠር", "owner.myListings": "የእኔ ዝርዝሮች", "owner.reviewHint": "አዲስ የሻጭ ዝርዝሮች በገበያው ላይ ከመታየታቸው በፊት በአስተዳዳሪ ይገመገማሉ።", "owner.submitReview": "ለግምገማ ላክ", "owner.empty": "ምንም ዝርዝር የለም። የመጀመሪያ ጨረታዎን ይፍጠሩ።", "owner.applied": "ማመልከቻው ተልኳል።", "owner.created": "ዝርዝሩ ተቀምጦ ለግምገማ ተልኳል።",
    "auction.title": "የጨረታ ዝርዝር", "auction.description": "የምርት ዝርዝር", "auction.seller": "ሻጭ", "auction.fee": "የመሳተፊያ ክፍያ", "auction.range": "የጨረታ መጠን", "auction.maxBids": "የአካውንት ጨረታ ገደብ", "auction.start": "ይጀምራል", "auction.end": "ይዘጋል", "auction.currentCount": "የተመዘገቡ ጨረታዎች", "auction.placeBid": "ጨረታ አቅርብ", "auction.amount": "የጨረታዎ መጠን (ETB)", "auction.paymentRequired": "የግብይት ቁጥር ወይም የደረሰኝ ስክሪንሾት ለአስተዳዳሪ ግምገማ ያስገቡ። ከማረጋገጫ በኋላ ብቻ ይጫረቱ።", "auction.paymentReady": "የተረጋገጠ ክፍያ አለ", "auction.submitBid": "ጨረታ አስገባ", "auction.signInBid": "ለመጫረት ይግቡ", "auction.report": "ይህን ዝርዝር ሪፖርት አድርግ", "auction.reportTitle": "ይህን ዝርዝር ሪፖርት አድርግ", "auction.reportSubject": "ርዕስ", "auction.reportDetails": "ዝርዝር", "auction.sendReport": "ሪፖርት ላክ", "auction.timeClosed": "ይህ ጨረታ ጨረታ አይቀበልም።", "auction.bidSuccess": "ጨረታዎ በአገልጋዩ ተቀብሏል።",
    "winners.title": "የአሸናፊዎች ጋለሪ", "winners.subtitle": "ሊረጋገጡ የሚችሉ ማጣቀሻዎች ያላቸው የታተሙ ውጤቶች።", "winners.search": "ምርት፣ አሸናፊ ወይም ማጣቀሻ ፈልግ…", "winners.all": "ሁሉም ውጤቶች", "winners.winner": "አሸናፊ", "winners.none": "ልዩ ጨረታ የለም", "winners.empty": "እስካሁን የታተመ ውጤት የለም።", "winners.reference": "ማጣቀሻ", "winners.integrity": "የታማኝነት ሃሽ", "winners.bids": "ትክክለኛ ጨረታዎች", "winners.phone": "የተደበቀ ስልክ",
    "account.notifications": "ማሳወቂያዎች", "account.devices": "የገቡባቸው መሣሪያዎች", "account.ownerAccess": "የሻጭ መዳረሻ ያመልክቱ", "account.openOwner": "የሻጭ ፖርታል ክፈት", "account.markRead": "እንደተነበበ ምልክት አድርግ", "account.currentDevice": "ይህ መሣሪያ", "account.reply": "የአስተዳዳሪ መልስ", "account.noNotifications": "ሁሉንም አንብበዋል።", "account.deviceBody": "ይህ አሳሽ ለመለያ ደህንነት ተመዝግቧል። የማያውቁትን መሣሪያ ያስወግዱ።",
    "admin.ownerApplications": "የሻጭ ማመልከቻዎች", "admin.listingReview": "ዝርዝር ግምገማ", "admin.ownerApprove": "ሻጩን ፍቀድ", "admin.ownerReject": "ማመልከቻውን አትቀበል", "admin.approveListing": "ፍቀድና አትም", "admin.rejectListing": "ዝርዝሩን አትቀበል", "admin.reply": "ለተጠቃሚው መልስ", "admin.privateNote": "የግል አስተዳዳሪ ማስታወሻ", "admin.saveReview": "መልሱን አስቀምጥ", "admin.ownerPending": "ግምገማ በመጠባበቅ ላይ", "admin.noApplications": "የሚጠባበቁ ማመልከቻዎች የሉም።", "admin.noListings": "ግምገማ የሚጠባበቁ ዝርዝሮች የሉም።",
    "form.title": "የምርት ርዕስ", "form.category": "ምድብ", "form.description": "የምርት መግለጫ", "form.seller": "የሻጭ ስም", "form.image": "የምርት ምስል", "form.imageHint": "JPEG, PNG ወይም WebP፤ ተጨምቆ ከ300 KB በታች በFirestore ይቀመጣል", "form.fee": "የጨረታ ክፍያ (ETB)", "form.minimum": "ዝቅተኛ ጨረታ (ETB)", "form.maximum": "ከፍተኛ ጨረታ (ETB)", "form.limit": "የተጠቃሚ ጨረታ ገደብ", "form.opens": "የመክፈቻ ጊዜ", "form.closes": "የመዝጊያ ጊዜ", "form.createDraft": "ረቂቅ አስቀምጥ", "form.uploading": "ምስልን ለFirestore በማዘጋጀት ላይ…", "form.saving": "በማስቀመጥ ላይ…", "form.imageRequired": "መጀመሪያ የምርት ምስል ይምረጡ።",
    "notice.bidAccepted.title": "ጨረታ ተቀብለናል", "notice.bidAccepted.body": "በ {title} ላይ የ {amount} ETB ጨረታዎ ተመዝግቧል።", "notice.auctionResult.title": "የጨረታ ውጤት ታትሟል", "notice.auctionResult.body": "የ {title} ውጤት አሁን ይገኛል።", "notice.reportUpdate.title": "የድጋፍ ሪፖርት ተዘምኗል", "notice.reportUpdate.body": "ሪፖርትዎ “{subject}” አሁን {status} ነው።", "notice.ownerApproved.title": "የሻጭ መዳረሻ ተፈቅዷል", "notice.ownerApproved.body": "የሻጭ ፖርታል መዳረሻዎ ንቁ ነው። ዝርዝር መፍጠር ይችላሉ።", "notice.ownerRejected.title": "የሻጭ ማመልከቻ ማሻሻያ", "notice.ownerRejected.body": "የሻጭ ማመልከቻዎ አልተፈቀደም። የአስተዳዳሪ ማስታወሻውን በመለያዎ ይመልከቱ።", "notice.auctionApproved.title": "ዝርዝሩ ተፈቅዷል", "notice.auctionApproved.body": "ዝርዝርዎ {title} ተፈቅዶ ታትሟል።", "notice.auctionRejected.title": "ዝርዝሩ ማሻሻያ ይፈልጋል", "notice.auctionRejected.body": "ዝርዝርዎ {title} ለግምገማ ተመልሷል። {note}", "notice.paymentApproved.title": "ክፍያው ተረጋግጧል", "notice.paymentApproved.body": "ለ {auction} የከፈሉት ክፍያ ተረጋግጧል። አሁን መጫረት ይችላሉ።", "notice.paymentRejected.title": "የክፍያ ማስረጃው አልጸደቀም", "notice.paymentRejected.body": "ለ {auction} የላኩት ማስረጃ አልጸደቀም። እርዳታ ከፈለጉ ድጋፍን ያነጋግሩ። {note}", "notice.default.title": "የ Cherta ማሻሻያ", "notice.default.body": "በመለያዎ አዲስ ማሻሻያ አለ።"
  }
};

type LanguageContextValue = { language: Language; setLanguage: (next: Language) => void };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => typeof localStorage !== "undefined" && localStorage.getItem("cherta-language") === "am" ? "am" : "en");
  const setLanguage = (next: Language) => {
    setLanguageState(next);
    localStorage.setItem("cherta-language", next);
  };
  useEffect(() => {
    const onStorage = (event: StorageEvent) => { if (event.key === "cherta-language") setLanguageState(event.newValue === "am" ? "am" : "en"); };
    window.addEventListener("storage", onStorage);
    return () => window.removeEventListener("storage", onStorage);
  }, []);
  const value = useMemo(() => ({ language, setLanguage }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider.");
  return value;
}

export function tr(key: string, language: Language, params: Record<string, string | number> = {}) {
  let value = messages[language][key] ?? messages.en[key] ?? key;
  for (const [name, replacement] of Object.entries(params)) value = value.replaceAll(`{${name}}`, String(replacement));
  return value;
}
