import { FormEvent, useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { useLocation } from "wouter";
import { ArrowLeft, ArrowUpRight, CheckCircle2, Clock3, Globe2, Heart, LogOut, MapPin, Phone, Save, ShieldCheck, Sparkles, Trophy, UserRound, Bell, Laptop2, Trash2, ExternalLink } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { getAccountData, listUserPayments, listUserReports, markNotificationRead, registerCurrentDevice, removeUserDevice, saveAccountProfile, submitUserReport, type AccountProfile, type ReportRecord } from "@/lib/firebaseData";
import { tr, useLanguage } from "@/lib/i18n";
import FirestoreImage from "@/components/FirestoreImage";

export default function Account() {
  const [, setLocation] = useLocation();
  const { user, loading, logout, isSuspended, isOwner, isAdmin } = useAuth();
  const { language, setLanguage } = useLanguage();
  const queryClient = useQueryClient();
  const accountQuery = useQuery({ queryKey: ["firestore-account", user?.uid], queryFn: () => getAccountData(user!.uid), enabled: Boolean(user) });
  const paymentQuery = useQuery({ queryKey: ["firestore-user-payments", user?.uid], queryFn: () => listUserPayments(user!.uid), enabled: Boolean(user) });
  const reportsQuery = useQuery({ queryKey: ["firestore-reports", user?.uid], queryFn: () => listUserReports(user!.uid), enabled: Boolean(user) });
  const [phone, setPhone] = useState("");
  const [city, setCity] = useState("");
  const [marketingOptIn, setMarketingOptIn] = useState(false);
  const [saving, setSaving] = useState(false);
  const [reportCategory, setReportCategory] = useState<ReportRecord["category"]>("other");
  const [reportSubject, setReportSubject] = useState("");
  const [reportDetails, setReportDetails] = useState("");
  const [submittingReport, setSubmittingReport] = useState(false);
  const initials = (user?.name ?? "TC").split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const t = (key: string, params?: Record<string, string | number>) => tr(key, language, params);

  useEffect(() => { if (!loading && !user) setLocation("/signin"); }, [loading, user, setLocation]);
  useEffect(() => {
    const profile = accountQuery.data?.profile;
    if (!profile) return;
    setPhone(profile.phone ?? ""); setCity(profile.city ?? ""); setMarketingOptIn(profile.marketingOptIn);
    if (profile.language !== language) setLanguage(profile.language);
  }, [accountQuery.data?.profile]);
  useEffect(() => {
    if (!user || isSuspended) return;
    void registerCurrentDevice(user.uid).then(() => queryClient.invalidateQueries({ queryKey: ["firestore-account", user.uid] })).catch((error) => console.warn("[Firestore] Device registration failed", error));
  }, [user?.uid, isSuspended, queryClient]);

  const handleSave = async (event: FormEvent) => {
    event.preventDefault(); if (!user || isSuspended) return;
    setSaving(true);
    const profile: AccountProfile = { phone: phone.trim() || null, city: city.trim() || null, language, marketingOptIn };
    try { await saveAccountProfile(user.uid, profile); setLanguage(language); await queryClient.invalidateQueries({ queryKey: ["firestore-account", user.uid] }); toast.success(language === "am" ? "የመለያ መረጃው ተቀምጧል።" : "Account details saved."); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Could not save account details."); }
    finally { setSaving(false); }
  };
  const handleLogout = async () => { await logout(); toast.success(language === "am" ? "ወጥተዋል።" : "You are signed out."); setLocation("/"); };
  const handleSubmitReport = async (event: FormEvent) => {
    event.preventDefault(); if (!user || isSuspended) return;
    setSubmittingReport(true);
    try { await submitUserReport(user.uid, { category: reportCategory, subject: reportSubject, details: reportDetails }); setReportSubject(""); setReportDetails(""); await queryClient.invalidateQueries({ queryKey: ["firestore-reports", user.uid] }); toast.success(language === "am" ? "ሪፖርቱ ለአስተዳዳሪ ተልኳል።" : "Report sent to the administrator."); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Could not submit report."); }
    finally { setSubmittingReport(false); }
  };
  const handleRead = async (notificationId: string) => {
    if (!user || isSuspended) return;
    try { await markNotificationRead(user.uid, notificationId); await queryClient.invalidateQueries({ queryKey: ["firestore-account", user.uid] }); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Could not mark notification as read."); }
  };
  const handleRemoveDevice = async (deviceId: string) => {
    if (!user || isSuspended) return;
    try { await removeUserDevice(user.uid, deviceId); await queryClient.invalidateQueries({ queryKey: ["firestore-account", user.uid] }); toast.success(language === "am" ? "መሣሪያው ተወግዷል።" : "Device removed."); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Could not remove device."); }
  };

  if (loading || (user && accountQuery.isLoading)) return <div className="account-loading site-shell"><div className="account-loading-mark"><Sparkles size={19} /></div><strong>{language === "am" ? "መለያዎን በመጫን ላይ…" : "Loading your account…"}</strong><span>{language === "am" ? "የ Cherta እንቅስቃሴዎን በማዘጋጀት ላይ።" : "Getting your Cherta activity ready."}</span></div>;
  if (!user) return null;
  const accountData = accountQuery.data;
  const bids = accountData?.bids ?? [];
  const wins = accountData?.wins ?? [];
  const unread = accountData?.notifications.filter((notice) => !notice.readAt) ?? [];

  return <div className="account-page site-shell">
    <header className="account-header container"><a href="/" className="brand-lockup"><span className="brand-mark"><span className="brand-mark-dot" /><span className="brand-mark-line brand-mark-line-a" /><span className="brand-mark-line brand-mark-line-b" /></span><span><strong>Tesaka</strong><em>Cherta</em></span></a><div className="account-header-actions"><button className="account-logout" onClick={() => setLanguage(language === "en" ? "am" : "en")}><Globe2 size={15}/>{language === "en" ? "አማ" : "EN"}</button><a href="/" className="back-link"><ArrowLeft size={15} /> {t("common.back")}</a><button className="account-logout" onClick={() => void handleLogout()}><LogOut size={15} /> {t("common.signOut")}</button></div></header>
    <main className="container account-main">
      <div className="account-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> {language === "am" ? "የ Cherta መለያዎ" : "Your Cherta account"}</div><h1>{language === "am" ? "እንኳን ደህና መጡ፣ " : "Good to see you, "}<em>{user.name.split(" ")[0]}.</em></h1><p>{language === "am" ? "መገለጫዎን ያስተዳድሩ፣ ጨረታዎችን ይከታተሉ፣ አስፈላጊ ማሳወቂያዎችን ይመልከቱ።" : "Manage your profile, track bids, and keep your next smart move close."}</p></div><div className="account-secure-pill"><ShieldCheck size={15} /> Firebase account</div></div>
      {isSuspended && <div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{language === "am" ? "መለያዎ ታግዷል። የመለያ ማሻሻያ፣ ሪፖርትና ጨረታ ተሰናክለዋል።" : "This account is suspended. Profile updates, reports, and bidding are disabled; contact the Cherta administrator."}</div>}
      {accountQuery.isError && <div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{language === "am" ? "Firestore መረጃውን ማምጣት አልተቻለም።" : "Could not load Firestore account data. Check Firebase Authentication and Firestore security rules."}</div>}
      <div className="account-grid">
        <section className="profile-card account-card"><div className="profile-card-top"><div className="account-avatar">{initials}</div><div><h2>{user.name}</h2><p>{user.email ?? "Email provided by Firebase Auth"}</p></div></div><div className="profile-rule" /><form onSubmit={(event) => void handleSave(event)} className="profile-form"><div className="account-field"><label htmlFor="phone"><Phone size={14} /> {language === "am" ? "ስልክ ቁጥር" : "Phone number"}</label><input id="phone" value={phone} disabled={isSuspended} onChange={(event) => setPhone(event.target.value)} placeholder="+251 9…" /></div><div className="account-field"><label htmlFor="city"><MapPin size={14} /> {language === "am" ? "ከተማ" : "City"}</label><input id="city" value={city} disabled={isSuspended} onChange={(event) => setCity(event.target.value)} placeholder="Addis Ababa" /></div><div className="account-field"><label htmlFor="language"><Globe2 size={14} /> {language === "am" ? "ቋንቋ" : "Preferred language"}</label><select id="language" value={language} disabled={isSuspended} onChange={(event) => setLanguage(event.target.value as "en" | "am")}><option value="en">English</option><option value="am">አማርኛ</option></select></div><label className="check-row"><input type="checkbox" checked={marketingOptIn} disabled={isSuspended} onChange={(event) => setMarketingOptIn(event.target.checked)} /><span>{language === "am" ? "ስለ አዲስ ጨረታና አሸናፊዎች ዜና ላኩልኝ።" : "Send me new-auction updates and winner stories."}</span></label><button className="primary-button account-save" disabled={saving || isSuspended}><Save size={15} /> {saving ? t("common.loading") : language === "am" ? "የመለያ መረጃ አስቀምጥ" : "Save account details"}</button></form>
          <div className="mt-5 border-t border-[#eee6d8] pt-4"><strong className="text-sm">{language === "am" ? "የሻጭ መዳረሻ" : "Seller access"}</strong><p className="mt-1 text-xs leading-5 text-[#737e73]">{isOwner ? (language === "am" ? "የተፈቀደ ሻጭ ነዎት።" : "Your seller portal is enabled.") : (language === "am" ? "የሻጭ ፖርታል ለመክፈት ማመልከቻ ያቅርቡ።" : "Apply for review to create product listings.")}</p><a href="/owner" className="mt-3 inline-flex items-center gap-2 rounded-full border border-[#cddcc8] px-4 py-2 text-xs font-bold text-[#0b5f4a]">{isOwner ? t("account.openOwner") : t("account.ownerAccess")} <ExternalLink size={13}/></a></div>
        </section>
        <section className="activity-card account-card"><div className="account-card-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> {language === "am" ? "የእንቅስቃሴ ታሪክ" : "Your activity"}</div><h2>{language === "am" ? "የጨረታ ታሪክ" : "Bid history"}</h2></div><span className="activity-count">{bids.length} {language === "am" ? "ጨረታዎች" : "bids"}</span></div>{bids.length ? <div className="activity-list">{bids.map((bid) => <a className="activity-row" key={bid.id} href={`/auction/${bid.auctionId}`}><FirestoreImage imagePath={bid.auctionImagePath} alt="" /><div className="activity-row-copy"><strong>{bid.auctionTitle}</strong><span><Clock3 size={12} /> {bid.createdAt.toLocaleDateString()}</span></div><div className="activity-row-amount"><strong>{bid.amount.toFixed(2)} ETB</strong><span className={`result-tag ${bid.isWinningBid ? "tag-live" : bid.auctionStatus === "live" ? "tag-live" : ""}`}>{bid.isWinningBid ? t("winners.winner") : bid.auctionStatus === "live" ? "Live" : "Closed"}</span></div></a>)}</div> : <div className="account-empty"><div className="empty-icon"><Clock3 size={18} /></div><strong>{language === "am" ? "ጨረታ አልቀረበም" : "No bids yet"}</strong><span>{language === "am" ? "የመጀመሪያ ጨረታዎ እዚህ ይታያል።" : "When you make your first bid, it will show here."}</span>{!accountQuery.isError && <a href="/#auctions" className="text-button">{language === "am" ? "ቀጥታ ጨረታ ፈልግ" : "Find a live auction"} <ArrowUpRight size={14} /></a>}</div>}</section>
        <section className="saved-card account-card"><div className="account-card-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> Outcomes</div><h2>{language === "am" ? "ያሸነፍኳቸው" : "Won auctions"}</h2></div><Sparkles size={18} className="saved-heart" /></div>{wins.length ? <div className="saved-list">{wins.map((win) => <a href={`/auction/${win.auctionId}`} className="saved-row" key={win.id}><FirestoreImage imagePath={win.imagePath} alt="" /><span><strong>{win.title}</strong><small>{win.amount.toFixed(2)} ETB · {win.createdAt.toLocaleDateString()}</small></span><Trophy size={15} /></a>)}</div> : <div className="account-empty compact"><div className="empty-icon amber-icon"><Sparkles size={18} /></div><strong>{language === "am" ? "እስካሁን ድል የለም" : "No wins yet"}</strong><span>{language === "am" ? "ውጤቱ ከታተመ በኋላ ድሎችዎ እዚህ ይታያሉ።" : "Winning bids appear here after the auction result is published."}</span></div>}</section>
        <section className="saved-card account-card"><div className="account-card-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> Keep watching</div><h2>{language === "am" ? "የተቀመጡ ጨረታዎች" : "Saved auctions"}</h2></div><Heart size={18} className="saved-heart" /></div>{accountData?.savedAuctions.length ? <div className="saved-list">{accountData.savedAuctions.map((auction) => <a href={`/auction/${auction.auctionId}`} className="saved-row" key={auction.id}><FirestoreImage imagePath={auction.imagePath} alt="" /><span><strong>{auction.title}</strong><small>Ends {auction.endsAt.toLocaleDateString()}</small></span><ArrowUpRight size={15} /></a>)}</div> : <div className="account-empty compact"><div className="empty-icon amber-icon"><Heart size={18} /></div><strong>{language === "am" ? "ምንም አልተቀመጠም" : "Nothing saved yet"}</strong><span>{language === "am" ? "በጨረታ ላይ ያለውን የልብ ምልክት ይጫኑ።" : "Tap the heart on an auction to keep it close."}</span><a href="/#auctions" className="text-button">Browse auctions <ArrowUpRight size={14} /></a></div>}</section>
        <section className="account-trust-card"><div className="account-trust-icon"><CheckCircle2 size={20} /></div><div><strong>{language === "am" ? "መለያዎ ደህንነቱ የተጠበቀ ነው።" : "Your account is yours."}</strong><p>Firebase Authentication protects sign-in and Firestore security rules isolate private account data.</p></div><UserRound size={42} className="account-trust-watermark" /></section>
      </div>
      <section className="mt-6 rounded-2xl border border-[#e6dccb] bg-[#fffdf8] p-5 sm:p-7"><div className="mb-4"><div className="eyebrow"><span className="eyebrow-line" /> {language === "am" ? "የክፍያ ሁኔታ" : "Payment verification"}</div><h2 className="mt-2 font-serif text-3xl">{language === "am" ? "የክፍያ ማስረጃዎች" : "Payment proofs"}</h2><p className="mt-1 text-sm text-[#737e73]">{language === "am" ? "OCR የጽሑፍ ጥቆማ ብቻ ነው፤ የክፍያ ማረጋገጫ አይደለም።" : "OCR is a text hint only, not payment verification."}</p></div><div className="grid gap-2">{paymentQuery.data?.map((payment) => <article key={payment.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-[#eee6d8] py-3"><div><strong className="text-sm">{payment.auctionTitle} · {payment.amount.toFixed(2)} ETB</strong><p className="mt-1 text-xs text-[#7b867c]">{payment.provider} · {payment.providerReference || (language === "am" ? "ማጣቀሻ የለም" : "no reference")} · {payment.createdAt.toLocaleString()}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${payment.status === "paid" ? "bg-[#e8f0e4] text-[#0b5f4a]" : payment.status === "failed" ? "bg-red-100 text-red-800" : "bg-[#fff1d8] text-[#8c5b1a]"}`}>{payment.used ? (language === "am" ? "ተጠቅሟል" : "used") : payment.status === "paid" ? (language === "am" ? "ተረጋግጧል" : "verified") : payment.status === "failed" ? (language === "am" ? "አልተቀበለም" : "rejected") : (language === "am" ? "በግምገማ ላይ" : "pending review")}</span></article>)}{!paymentQuery.data?.length && <p className="text-sm text-[#737e73]">{language === "am" ? "የክፍያ መዝገብ የለም።" : "No payment proofs submitted yet."}</p>}</div></section>
      <section className="mt-6 rounded-2xl border border-[#e6dccb] bg-[#fffdf8] p-5 sm:p-7"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><div className="eyebrow"><span className="eyebrow-line" /> <Bell size={13}/> {t("account.notifications")}</div><h2 className="mt-2 font-serif text-3xl">{t("account.notifications")}</h2><p className="mt-2 max-w-2xl text-sm text-[#737e73]">{unread.length ? `${unread.length} ${language === "am" ? "ያልተነበቡ" : "unread"}` : t("account.noNotifications")}</p></div></div><div className="grid gap-3">{accountData?.notifications.map((notice) => <article key={notice.id} className={`rounded-xl border p-4 ${notice.readAt ? "border-[#eee6d8] bg-white" : "border-[#cddcc8] bg-[#f5f9f2]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-sm">{t(notice.titleKey)}</strong><p className="mt-1 text-sm leading-5 text-[#596a5f]">{t(notice.bodyKey, notice.params)}</p><span className="mt-2 block text-[11px] text-[#7b867c]">{notice.createdAt.toLocaleString()}</span></div>{!notice.readAt && <button onClick={() => void handleRead(notice.id)} disabled={isSuspended} className="rounded-full border px-3 py-1.5 text-xs font-bold">{t("account.markRead")}</button>}</div></article>)}{!accountData?.notifications.length && <p className="rounded-xl bg-white p-5 text-sm text-[#737e73]">{t("account.noNotifications")}</p>}</div></section>
      <section className="mt-6 rounded-2xl border border-[#e6dccb] bg-[#fffdf8] p-5 sm:p-7"><div className="mb-4 flex items-center gap-3"><Laptop2 className="text-[#0b5f4a]"/><div><h2 className="font-serif text-3xl">{t("account.devices")}</h2><p className="mt-1 text-sm text-[#737e73]">{t("account.deviceBody")}</p></div></div><div className="grid gap-2">{accountData?.devices.map((device) => <article key={device.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-[#eee6d8] py-3"><div><strong className="text-sm">{device.label} {device.current && <span className="ml-2 rounded-full bg-[#e8f0e4] px-2 py-1 text-[10px] text-[#0b5f4a]">{t("account.currentDevice")}</span>}</strong><p className="mt-1 text-xs text-[#7b867c]">Last active {device.lastSeen.toLocaleString()}</p></div><button onClick={() => void handleRemoveDevice(device.id)} disabled={isSuspended || device.current} title={device.current ? t("account.currentDevice") : "Remove device"} className="inline-flex items-center gap-1 rounded-full border px-3 py-1.5 text-xs font-bold disabled:opacity-40"><Trash2 size={13}/> Remove</button></article>)}{!accountData?.devices.length && <p className="text-sm text-[#737e73]">{language === "am" ? "መሣሪያ ገና አልተመዘገበም።" : "No devices are registered yet."}</p>}</div></section>
      <section className="mt-6 rounded-2xl border border-[#e6dccb] bg-[#fffdf8] p-5 sm:p-7"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><div className="eyebrow"><span className="eyebrow-line" /> Help and safety</div><h2 className="mt-2 font-serif text-3xl">{language === "am" ? "ችግር ሪፖርት አድርግ" : "Report a problem"}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#737e73]">{language === "am" ? "የሪፖርት ዝርዝሩን አስተዳዳሪዎች ብቻ ማየት ይችላሉ። የይለፍ ቃል ወይም የካርድ መረጃ አያካትቱ።" : "Only administrators can read report details. Do not include passwords or payment-card details."}</p></div><span className="rounded-full bg-[#f1eee5] px-3 py-1.5 text-xs font-bold text-[#68766b]">{reportsQuery.data?.length ?? 0} reports</span></div>
        <form onSubmit={(event) => void handleSubmitReport(event)} className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Category<select value={reportCategory} disabled={isSuspended} onChange={(event) => setReportCategory(event.target.value as ReportRecord["category"])} className="rounded-lg border border-[#d7d8c9] bg-white px-3 py-2.5 text-sm font-normal"><option value="account">Account</option><option value="auction">Auction</option><option value="payment">Payment</option><option value="safety">Safety concern</option><option value="other">Other</option></select></label><label className="grid gap-1 text-xs font-bold">Subject<input required minLength={4} maxLength={160} disabled={isSuspended} value={reportSubject} onChange={(event) => setReportSubject(event.target.value)} className="rounded-lg border border-[#d7d8c9] bg-white px-3 py-2.5 text-sm font-normal" placeholder="Briefly describe the issue" /></label><label className="grid gap-1 text-xs font-bold md:col-span-2">Details<textarea required minLength={20} maxLength={4000} rows={5} disabled={isSuspended} value={reportDetails} onChange={(event) => setReportDetails(event.target.value)} className="rounded-lg border border-[#d7d8c9] bg-white px-3 py-2.5 text-sm font-normal" placeholder="Include relevant context, but do not include passwords or payment-card details." /></label><div className="flex items-center justify-between gap-3 md:col-span-2"><span className="text-xs text-[#7b867c]">Report data is written directly to Firestore.</span><button disabled={submittingReport || isSuspended} className="rounded-full bg-[#0b5f4a] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60">{submittingReport ? "Sending…" : "Submit report"}</button></div></form>
        <div className="mt-6 grid gap-2">{reportsQuery.data?.map((report) => <article key={report.id} className="border-t border-[#eee6d8] py-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong className="text-sm">{report.subject}</strong><p className="mt-1 text-xs text-[#7b867c]">{report.category} · {report.createdAt.toLocaleString()}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${report.status === "resolved" ? "bg-[#e8f0e4] text-[#0b5f4a]" : report.status === "dismissed" ? "bg-[#f1eee5] text-[#737e73]" : "bg-[#fff1d8] text-[#8c5b1a]"}`}>{report.status.replace("_", " ")}</span></div>{report.adminReply && <p className="mt-3 rounded-lg bg-[#f5f6ee] p-3 text-sm"><strong>{t("account.reply")}:</strong> {report.adminReply}</p>}</article>)}{reportsQuery.isError && <p className="border-t border-[#eee6d8] pt-3 text-xs text-[#9b3929]">Report history is temporarily unavailable.</p>}</div>
      </section>
    </main>
  </div>;
}
